name: build&all_tests
on: [pull_request, workflow_dispatch]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: desktop-business-app
          push: false
          load: true

      - name: Build Project
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace desktop-business-app /bin/bash -c "mkdir -p build && cd build && cmake ../modules/backend && make"

      - name: Run Unit Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/build desktop-business-app ctest
